version: "3.7"

services:
  web:
    build:
      context: .
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
    networks:
      - main_net
    ports:
      - 8989:8000
    commands: >
      bash -c "python manage.py makemigrations \
               && python manage.py migrate \
               && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASWORD: postgres
    networks:
      - main_net

networks:
  main_net:
