name: Lint app

on: pull_request

jobs:
  Lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.12
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Prepare cache
        uses: actions/cache@v2
        id: cache
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != true
        run: poetry install

      - name: Run black
        run: poetry run black .

      - name: Run flake8
        run: poetry run flake8 .
